nelmio_api_doc:
  documentation:
    info:
      title: "JobQuest API Documentation"
      description: "API documentation for JobQuest"
      version: "1.0.0"
      prefix: "/api"

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
