version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: jobquest-backend
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: 46fcc42ff552fa1c90d556f641bcc5af
      DATABASE_URL: "mysql://bastien:root@database:3306/job_board?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image: mariadb:10.11
    container_name: jobquest-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_board
      MYSQL_USER: bastien
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
